# Generated by Django 4.2.8 on 2024-01-09 11:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True, verbose_name='slug')),
                ('url', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='url')),
                ('is_default', models.BooleanField(blank=True, default=False, verbose_name='default status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='daily rate')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='deposit')),
                ('is_available', models.BooleanField(blank=True, default=False, verbose_name='availability status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(blank=True, verbose_name='rental date')),
                ('return_date', models.DateField(blank=True, verbose_name='return date')),
                ('days_rented', models.PositiveIntegerField(blank=True, default=1, verbose_name='days rented')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='total cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'rental',
                'verbose_name_plural': 'rentals',
            },
        ),
    ]
